def checking_lives(lives,name):
    if lives == 5:
        print(f'Hey {name}, Save me From Hanging! Ah my legs !')
        print('#######################')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('      #   #        ##  ')
        print('     #     #       ##  ')
        print('    #       #      ##  ')
        print('   #         #     ##  ')
        print('                   ##  ')
    elif lives == 4:
        print(f'Hey {name}, Save me From Hanging! Ah my torso ! ')
        print('#######################')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('       ###         ##  ')
        print('       ###         ##  ')
        print('       ###         ##  ')
        print('       ###         ##  ')
        print('       ###         ##  ')
        print('      #   #        ##  ')
        print('     #     #       ##  ')
        print('    #       #      ##  ')
        print('   #         #     ##  ')
        print('                   ##  ')
    elif lives == 3:
        print(f'Hey {name}, Save me From Hanging! Ah my body ! ')
        print('#######################')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('                   ##  ')
        print('      #####        ##  ')
        print('     # ### #       ##  ')
        print('    #  ###  #      ##  ')
        print('   #   ###   #     ##  ')
        print('       ###         ##  ')
        print('      #   #        ##  ')
        print('     #     #       ##  ')
        print('    #       #      ##  ')
        print('   #         #     ##  ')
        print('                   ##  ')
    elif lives == 2:
        print(f'Hey {name}, Save me From Hanging! Ah I am going to die save me ! ')
        print('#######################')
        print('                   ##  ')
        print('       ###         ##  ')
        print('      #####        ##  ')
        print('       ###         ##  ')
        print('      #####        ##  ')
        print('     # ### #       ##  ')
        print('    #  ###  #      ##  ')
        print('   #   ###   #     ##  ')
        print('       ###         ##  ')
        print('      #   #        ##  ')
        print('     #     #       ##  ')
        print('    #       #      ##  ')
        print('   #         #     ##  ')
        print('                   ##  ')
    elif lives == 1:
        print(f'Hey {name}, Save me From Hanging! Ah I am getting hanged now ! ')
        print('#######################')
        print('            #      ##  ')
        print('       ###  #      ##  ')
        print('      ##### #      ##  ')
        print('       ######      ##  ')
        print('      #####        ##  ')
        print('     # ### #       ##  ')
        print('    #  ###  #      ##  ')
        print('   #   ###   #     ##  ')
        print('       ###         ##  ')
        print('      #   #        ##  ')
        print('     #     #       ##  ')
        print('    #       #      ##  ')
        print('   #         #     ##  ')
        print('                   ##  ')
    elif lives == 0:
        print('REST IN PEACE !! .....')
        print('#######################')
        print('            #      ##  ')
        print('       ###  #      ##  ')
        print('      ##### #      ##  ')
        print('       ######      ##  ')
        print('      #####        ##  ')
        print('     # ### #       ##  ')
        print('    #  ###  #      ##  ')
        print('   #   ###   #     ##  ')
        print('       ###         ##  ')
        print('      #   #        ##  ')
        print('     #     #       ##  ')
        print('    #       #      ##  ')
        print('   #         #     ##  ')
        print('                   ##  ')
        print('\n\n You are an Evil, You let a man get hunged! ')

def congo(name):
        print('                   ')
        print('       ###         ')
        print('      #####        ')
        print('       ###         ')
        print('      #####        ')
        print(f'     # ### #       Thank you for Saving me, {name}')
        print('    #  ###  #      ')
        print('   #   ###   #     ')
        print('       ###         ')
        print('      #   #        ')
        print('     #     #       ')
        print('    #       #      ')
        print('   #         #     ')
        print('                   ')
        